name: Deploy to S3
on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}/${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16.15.1
  CACHE_WEB_NAME: web

jobs:
  deploy:
    name: Deploy Website to S3
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache web dependencies
        id: web-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ env.CACHE_WEB_NAME }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.web-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Compile & build
        run: npm run build
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: aws s3 cp --recursive dist s3://taskana.pro
      - name: Invalidate AWS CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.DISTRIBUTION_ID }} --paths /
